version: "3.10"
services:
  cum-client:
    build: .
    image: cum-client
    container_name: cum_client_c
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    